### ISSUE TITLE
Remove Domain.Common (moved content to Domain)

### ISSUE THREAD

**Issue by linus-rundberg** [Cloud-Nine/crayon-api-sdk#8] opened 2016-05-19 13:29 UTC
- [x] Namespace removed https://github.com/Cloud-Nine/crayon-api-sdk/commit/8a2dbfec791c83c90305c5a1710314f8f9cef5e3

**Comment by kristoferk** [comment] 2016-06-05 23:12
Duplicate of  #10

**Closed by kristoferk** 2016-06-05 23:12 UTC
Labels: duplicate
