### ISSUE TITLE
Ta bort Exceptions namespace

### ISSUE THREAD

**Issue by linus-rundberg** [Cloud-Nine/crayon-api-sdk#5] opened 2016-05-19 13:03 UTC
- [x] Namespace borttaget https://github.com/Cloud-Nine/crayon-api-sdk/commit/c38b177966ad9088a3a0cd9fe26f8ed48af2420d

**Comment by kristoferk** [comment] 2016-06-06 00:00
Duplicate of  Flatten namespaces #10

**Closed** 2016-06-06 00:00 UTC
Labels: duplicate
